-- ============================================================
-- Supabase setup for annotation tool
-- Table: annotations
-- ============================================================

create table if not exists public.annotations (
    id bigint generated by default as identity primary key,
    annotator_name text not null,
    sample_id text not null,
    text_content text not null default '',
    human_label int,
    labeled_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 同一标注员对同一条样本只能有一条记录
create unique index if not exists ux_annotations_annotator_sample
on public.annotations (annotator_name, sample_id);

-- 更新时间自动维护
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    if tg_op = 'INSERT' and new.labeled_at is null then
        new.labeled_at = now();
    end if;
    return new;
end;
$$;

drop trigger if exists trg_annotations_updated_at on public.annotations;
create trigger trg_annotations_updated_at
before insert or update on public.annotations
for each row execute function public.set_updated_at();

-- RLS: 简化可用版本（先跑通）
alter table public.annotations enable row level security;

-- 注意：以下策略允许 anon key 进行读写，适合内部临时工具。
-- 正式生产请改为基于 auth.uid() 的更严格访问控制。
drop policy if exists "annotations_select_all" on public.annotations;
create policy "annotations_select_all"
on public.annotations
for select
to anon, authenticated
using (true);

drop policy if exists "annotations_insert_all" on public.annotations;
create policy "annotations_insert_all"
on public.annotations
for insert
to anon, authenticated
with check (true);

drop policy if exists "annotations_update_all" on public.annotations;
create policy "annotations_update_all"
on public.annotations
for update
to anon, authenticated
using (true)
with check (true);
